export const IMAGE_PREVIEW_SIZE = 8388608; // 8MiB
export const IMAGE_PREVIEW_MIMES = ['image/jpeg', 'image/png'];
export const UPLOAD_POSTER_SIZE = 3145728; // 3MiB
export const UPLOAD_BACKDROP_SIZE = 5242880; // 5MiB
export const UPLOAD_STILL_SIZE = 2097152; // 2 MiB
export const UPLOAD_POSTER_MIN_WIDTH = 500;
export const UPLOAD_POSTER_MIN_HEIGHT = 750;
export const UPLOAD_BACKDROP_MIN_WIDTH = 1280;
export const UPLOAD_BACKDROP_MIN_HEIGHT = 720;
export const UPLOAD_POSTER_ASPECT_WIDTH = 2;
export const UPLOAD_POSTER_ASPECT_HEIGHT = 3;
export const UPLOAD_BACKDROP_ASPECT_WIDTH = 16;
export const UPLOAD_BACKDROP_ASPECT_HEIGHT = 9;
export const UPLOAD_STILL_MIN_WIDTH = 640;
export const UPLOAD_STILL_MIN_HEIGHT = 360;
export const UPLOAD_STILL_ASPECT_WIDTH = 16;
export const UPLOAD_STILL_ASPECT_HEIGHT = 9;
export const UPLOAD_SUBTITLE_SIZE = 512000;
export const UPLOAD_SUBTITLE_EXT = '.vtt';
export const UPLOAD_MEDIA_SOURCE_MAX_SIZE = 42949672960;
export const UPLOAD_MEDIA_SOURCE_EXT = ['.mp4', '.mkv', '.webm', '.m2ts'];
export const EPISODE_LIST_INIT_SIZE = 10;
export const YOUTUBE_EMBED_URL = 'https://www.youtube.com/embed/';
export const YOUTUBE_THUMBNAIL_URL = 'https://img.youtube.com/vi/';
export const QUEUE_UPLOAD_CHUNK_SIZE = 10485760; // 10MiB
export const QUEUE_UPLOAD_RETRIES = 5;
export const QUEUE_UPLOAD_RETRY_DELAY = 3000;
