import type { Genre } from './genre.model';
import type { MovieStatus } from './movie-status.model';
import type { ShortDate } from './short-date.model';
import type { TVShowListInfo } from './tv-show-list-info.model';

export interface Media {
  _id: string;
  type: string;
  title: string;
  originalTitle?: string;
  slug: string;
  overview: string;
  runtime: number;
  genres: Genre[];
  originalLang?: string;
  adult: boolean;
  releaseDate: ShortDate;
  movie: MovieStatus;
  tv: TVShowListInfo;
  views: number;
  dailyViews: number;
  weeklyViews: number;
  monthlyViews: number;
  ratingCount: number;
  ratingAverage: number;
  posterUrl?: string;
  thumbnailPosterUrl?: string;
  smallPosterUrl?: string;
  fullPosterUrl?: string;
  posterColor?: number;
  posterPlaceholder?: string;
  backdropUrl?: string;
  thumbnailBackdropUrl?: string;
  smallBackdropUrl?: string;
  fullBackdropUrl?: string;
  backdropColor?: number;
  backdropPlaceholder?: string;
  pStatus?: number;
  createdAt: Date;
  updatedAt: Date;
  _translated?: boolean;
}
